### ISSUE TITLE
Enable data extraction from excel files that are encrypted (xls) 

### ISSUE THREAD

**Issue by wenshyan** [sakai-to/node-red-contrib-spreadsheet-in#13]
Hello. Would like to ask if it is possible for this node red node to pull data from an excel file which is encrypted (.xls). How would we go about it?

**Comment by sakai-to** [comment]
@wenshyan Thank you for the question and please allow me to clarify my understanding. By excel files which are encrypted do you mean password-protected files?
If so, this node is currently not intended to read such files. But I would like to see if it can be implemented.

**Comment by sakai-to** [comment]
This node uses SheetJS Community Edition to read excel files. Accoring to its [document](https://docs.sheetjs.com/docs/api/parse-options), currently only XOR encryption is supported. This seems to imply that it supports Excel 95 and earlier editions. I think most people use editions newer than Excel 95 so that it is useless for most people to support decryption with SheetJS. Also, I don't know any library that can replace SheetJS. Therefore, I decided not to support this enhancement at this time.
